[package]
name = "iomux"
version = "0.1.0"
authors = ["nathan <nathan+dev@electriccoin.co>"]
edition = "2018"

[dependencies]
derive_more = "0.13.0"
futures-util = "*"
tokio = { version = "=0.2.0-alpha.6", features = ["process"] }
